# Generated by Django 3.2.25 on 2024-06-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description_short', models.TextField(verbose_name='Краткое описание')),
                ('description_long', models.TextField(verbose_name='Полное описание')),
                ('lng', models.FloatField(verbose_name='Координаты (долгота)')),
                ('lat', models.FloatField(verbose_name='Координаты (широта)')),
            ],
            options={
                'verbose_name': 'Место для посещения',
                'verbose_name_plural': 'Места для посещения',
                'ordering': ['title'],
            },
        ),
    ]
