# Generated by Django 3.2.25 on 2024-06-05 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('ordinal', models.PositiveIntegerField(default=1, verbose_name='Порядковый номер')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageries', to='places.place', verbose_name='Место для посещения')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['place', 'ordinal'],
            },
        ),
    ]
