# Generated by Django 3.2.25 on 2024-06-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_imagery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagery',
            name='image',
            field=models.ImageField(upload_to='static/images/', verbose_name='Изображение'),
        ),
    ]
