# Generated by Django 3.2.25 on 2024-06-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_imagery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagery',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Изображение'),
        ),
    ]
